baseURL = "http://www.merryferryconsult.cl"
languageCode = "en"
defaultContentLanguage = "en"
title = "Merryferry Consult"
theme = "hallo"

[Author]
    name = "Maria Fally"

[params]
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/maria-fally"

   [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:mefeconsult@gmail.com"

    greeting = "Greetings!"